<a href="https://colab.research.google.com/github/prafullkatiyar/ML-Notes/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Numpy's Structured Array


In [19]:
# Lesson 1
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [11]:
# Return a new array of given shape and type, filled with zeros.
x = np.zeros(4, dtype=int)
print(x)

[0 0 0 0]


In [20]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [21]:
# Assign data to structured array
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [22]:
# BOOLEAN masking, get names where age is under 30
data[data['age'] < 30]

array([('Alice', 25, 55. ), ('Doug', 19, 61.5)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

# Array types

In [23]:
a = np.array([1, 2, 3])   # Create a rank 1 array
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
c = np.zeros((3,2))   # Create an array of all zeros
d = np.ones((3,2))    # Create an array of all ones
e = np.full((2,2), 7)  # Create a constant array
f = np.eye(2)         # Create a 2x2 identity matrix

# Slice Arrays

In [28]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# Slice the subarray consisting of the first 2 rows and columns 1 and 2; 
b = a[:2, 1:3] 
b

array([[2, 3],
       [6, 7]])

In [35]:
# Rank 1 view of the second row of a
row_r1 = a[1, :]
print(row_r1)

[5 6 7 8]


In [34]:
# index 
print(a[[0, 1, 2], [0, 1, 0]])

[1 6 9]


In [36]:
g = np.array([a[0, 0], a[1, 1], a[2, 0]])
g

array([1, 6, 9])

In [37]:
h = a[[0, 0], [1, 1]] 
h

array([2, 2])

In [38]:
i = np.array([a[0, 1], a[0, 1]])
i

array([2, 2])

In [40]:
bool_idx = (a > 5)
bool_idx

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [41]:
j = a[bool_idx]
j

array([ 6,  7,  8,  9, 10, 11, 12])

In [42]:
k = a[a > 5]
k

array([ 6,  7,  8,  9, 10, 11, 12])

# Element wise opertaions

In [43]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [44]:
print("Elementwise sum; both produce the array")
print(x + y)
print(np.add(x, y))

Elementwise sum; both produce the array
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [45]:
print("Elementwise difference; both produce the array")
print(x - y)
print(np.subtract(x, y))

Elementwise difference; both produce the array
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [46]:
print("Elementwise product; both produce the array")
print(x * y)
print(np.multiply(x, y))

Elementwise product; both produce the array
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [47]:
print("Elementwise division; both produce the array")
print(x / y)
print(np.divide(x, y))

Elementwise division; both produce the array
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [48]:
print("Elementwise square root; produces the array")
print(np.sqrt(x))

Elementwise square root; produces the array
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [50]:
v = np.array([9,10])
w = np.array([11, 12])
v.dot(w)

219

In [52]:
# dot is available both as a function in the numpy module and 
# as an instance method of array objects
np.dot(v, w)

219

# Broadcasting

In [53]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=x+v
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

# Create numpy array/ sampling

In [54]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [55]:
y = x[::-1]
y

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [56]:
x = np.random.random(10)
x

array([0.84348227, 0.03204596, 0.98812999, 0.92856638, 0.7901312 ,
       0.810561  , 0.05502279, 0.40274897, 0.15091627, 0.67026539])

In [57]:
x.max()

0.988129986809845

In [58]:
x.argmax()

2

In [60]:
ages = np.random.randint(low=20, high=60, size=10)
ages

array([21, 20, 48, 50, 55, 32, 41, 36, 41, 34])

In [64]:
# used with matplot lib to generate 
# evenly spaced 256 number in an interval of -6 to 6
x = np.linspace(-6,6,256) 

In [66]:
# array from -5 to 5, with interval of 0.1
xx = np.arange(-5, 5, 0.1)

In [67]:
# assume Y = 2Y + some perturbation
pp = 1.1  # level of noise
yy = xx**2 + np.random.normal(0, pp, size=len(xx))
# location of mean(default 0), standard deviation and shape
# sample of numbers drawn from normal distribution

# Other functions

In [69]:
d = np.array([1,2,3])
np.power(d, 2) # power function
np.sqrt(d.sum()) # square root function

2.449489742783178

In [75]:
# Draw random samples from a multivariate normal distribution.
# is a generalisation of the one-dimensional normal distribution to higher dimensions.
# params: mean covariance size
d = np.random.multivariate_normal(np.zeros(3), np.eye(3), size=5)
d

array([[-0.24962783,  1.94364075,  1.43261875],
       [-0.68908368, -0.47211293, -2.49346158],
       [ 1.01698755, -1.80975142, -1.56984662],
       [ 0.18880354,  0.92101836,  0.48866847],
       [-0.26361744, -1.57743083,  1.01989405]])

In [72]:
'''
np.r_
np.c_
np.ravel
np.reshape
'''

In [78]:
#You are allowed to have one "unknown" dimension.
#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
#Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [79]:
'''
np.linalg.norm(pos - pos_goal) 
generate matrix with one of the 8 available norms(ex eucleadian)
similar to distance matrix in from scipy.spatial import distance_matrix
'''

'\nnp.linalg.norm(pos - pos_goal) \ngenerate matrix with one of the 8 available norms(ex eucleadian)\nsimilar to distance matrix in from scipy.spatial import distance_matrix\n'